"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar.js";
import HamburgerButton from "@/components/HamburgerButton.js";
import { useState } from "react";
import { Toaster } from "react-hot-toast";
import { SensorDataProvider } from "@/contexts/SensorDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SensorDataProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <div className="min-h-screen bg-gray-50 dark:bg-gray-900 transition-colors">
            <Sidebar
              isOpen={isSidebarOpen}
              onClose={() => setIsSidebarOpen(false)}
            />
            <div className="flex flex-col flex-1 md:ml-64">
              <header className="flex items-center justify-between p-4 bg-white dark:bg-gray-800 border-b dark:border-gray-700 md:hidden transition-colors">
                <span className="text-xl font-bold text-gray-900 dark:text-white">Fish Monitor</span>
                <HamburgerButton onClick={() => setIsSidebarOpen(true)} />
              </header>
              <main className="p-4 sm:p-6 lg:p-10">{children}</main>
            </div>
          </div>
        </SensorDataProvider>
      </body>
    </html>
  );
}
